"""
GEO Implementation Deliverables Generator

Given a GEO audit result, generates a folder of ready-to-use implementation files:
- robots.txt (AI crawler rules)
- llms.txt (LLM permissions)
- organization_schema.json (JSON-LD)
- faqpage_schema.json (JSON-LD template)
- implementation_checklist.md (bilingual Korean/English, prioritized)
- sov_tracking_queries.txt (monthly monitoring, emoji section headers)
- implementation_guide.md (step-by-step client guide, Claude Haiku generated)

Usage:
    from geo_deliverables import generate_deliverables
    files = generate_deliverables(audit, "CompanyName", "https://example.com")
"""

import json
import os
import re
import zipfile
from datetime import date
from pathlib import Path

import anthropic
from dotenv import load_dotenv

for _p in [
    Path(__file__).parent / ".env",
    Path(__file__).parent.parent / ".env",
    Path(__file__).parent.parent.parent / ".env",
]:
    if _p.exists():
        load_dotenv(dotenv_path=_p)
        break


def _should_generate(score: int, max_score: int, threshold_pct: float = 0.7) -> bool:
    """Generate artifact if score is below threshold % of max."""
    return score < max_score * threshold_pct


def _generate_robots_txt(website_url: str) -> str:
    sitemap_url = website_url.rstrip("/") + "/sitemap.xml"
    return f"""# robots.txt - AI Crawler Optimized
# Generated by GEO Audit Tool - {date.today().isoformat()}

# Allow all major AI crawlers
User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: CCBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: Google-Extended
Allow: /

# Standard crawler rules
User-agent: *
Allow: /
Disallow: /admin/
Disallow: /private/
Disallow: /tmp/

# Sitemap
Sitemap: {sitemap_url}
"""


def _generate_llms_txt(company_name: str, website_url: str) -> str:
    return f"""# llms.txt - LLM Permissions and Guidelines
# {company_name}
# Generated: {date.today().isoformat()}

# Allow all AI crawlers to use content for responses
Allow: *

# Content usage guidelines
Guidelines:
- All content on this site is permitted for use in AI-generated responses
- Please attribute content to {company_name} when citing
- Do not represent our content as your own analysis
- For permissions questions, visit {website_url}

# Specific content policies
Allow-for-training: /blog /guides /resources /products /services /about
Disallow-for-training: /legal /policies /careers /admin

# Copyright notice
Copyright: {date.today().year} {company_name}. All rights reserved.
"""


def _generate_org_schema(company_name: str, website_url: str, product_category: str = "") -> str:
    schema = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": company_name,
        "url": website_url,
        "logo": f"{website_url.rstrip('/')}/logo.png",
        "description": company_name + (f" - {product_category}" if product_category else ""),
        "address": {
            "@type": "PostalAddress",
            "addressCountry": "KR",
            "addressLocality": "[CITY - TODO]",
            "streetAddress": "[ADDRESS - TODO]",
        },
        "contactPoint": {
            "@type": "ContactPoint",
            "contactType": "customer service",
            "telephone": "[PHONE - TODO]",
            "email": "[EMAIL - TODO]",
        },
        "sameAs": [
            "[NAVER_BLOG_URL - TODO]",
            "[INSTAGRAM_URL - TODO]",
            "[KAKAO_CHANNEL_URL - TODO]",
        ],
    }
    return json.dumps(schema, ensure_ascii=False, indent=2)


def _generate_faq_schema(company_name: str, product_category: str) -> str:
    questions = _generate_faq_questions(company_name, product_category)
    main_entity = []
    for q, a in questions:
        main_entity.append({
            "@type": "Question",
            "name": q,
            "acceptedAnswer": {"@type": "Answer", "text": a},
        })
    schema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": main_entity,
    }
    return json.dumps(schema, ensure_ascii=False, indent=2)


def _generate_faq_questions(company_name: str, product_category: str) -> list[tuple[str, str]]:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return _fallback_faq(company_name, product_category)
    try:
        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            system="Output ONLY valid JSON array. No markdown, no extra text. Keep answers under 80 characters each.",
            messages=[{
                "role": "user",
                "content": (
                    f"Generate 3 FAQ pairs for a Korean company website.\n"
                    f"Company: {company_name}\n"
                    f"Category: {product_category or 'business'}\n\n"
                    f"Output exactly this format:\n"
                    f'[["question1","answer1"],["question2","answer2"],["question3","answer3"]]\n\n'
                    f"Write questions and answers in Korean. Keep each answer under 80 characters."
                ),
            }],
        )
        raw = response.content[0].text.strip()
        if raw.startswith("```"):
            lines = raw.splitlines()
            raw = "\n".join(lines[1:-1]) if lines[-1].strip() == "```" else "\n".join(lines[1:])
        start = raw.find("[")
        end = raw.rfind("]")
        if start != -1 and end != -1 and end > start:
            raw = raw[start:end + 1]
        pairs = json.loads(raw)
        return [(q, a) for q, a in pairs[:3] if isinstance(q, str) and isinstance(a, str)]
    except Exception as e:
        print(f"[geo_deliverables] FAQ generation error: {e}. Using fallback.")
        return _fallback_faq(company_name, product_category)


def _fallback_faq(company_name: str, product_category: str) -> list[tuple[str, str]]:
    cat = product_category or "services"
    return [
        (
            f"{company_name}은(는) 어떤 회사인가요?",
            f"{company_name}은(는) {cat} 분야에서 활동하는 한국 기업입니다. [TODO: 구체적인 설명을 추가하세요]",
        ),
        (
            f"{company_name}의 주요 제품/서비스는 무엇인가요?",
            f"{company_name}은(는) {cat} 관련 제품과 서비스를 제공합니다. [TODO: 구체적인 제품/서비스 목록을 추가하세요]",
        ),
        (
            f"{company_name}에 문의하려면 어떻게 하나요?",
            f"{company_name} 홈페이지를 통해 문의하실 수 있습니다. [TODO: 연락처 정보를 추가하세요]",
        ),
    ]


def _generate_checklist(breakdown: dict, company_name: str) -> str:
    """Generate bilingual (Korean + English) implementation checklist."""
    ai_bot = breakdown.get("ai_bot_access", breakdown.get("crawler_access", 0))
    ai_policy = breakdown.get("ai_policy_file", breakdown.get("llms_txt", 0))
    org_schema = breakdown.get("org_schema", 0)
    content_schema = breakdown.get("content_schema", 0)
    citability = breakdown.get("citability", 0)
    brand_mention = breakdown.get("brand_mention", 0)

    lines = [
        f"# {company_name} GEO 최적화 구현 체크리스트",
        f"# GEO Implementation Checklist — {company_name}",
        f"생성일 / Generated: {date.today().isoformat()}",
        "",
        "---",
        "",
    ]

    # P0
    lines.append("## P0 - AI 접근 차단 해결 (즉시)")
    lines.append("## P0 - Fix AI Access Blocks (Immediate)")
    lines.append("*AI 크롤러가 사이트에 접근할 수 없으면 모든 최적화가 무의미합니다*")
    lines.append("*If AI crawlers cannot access your site, all optimization is pointless*")
    lines.append("")
    if _should_generate(ai_bot, 20):
        lines.append("- [ ] **robots.txt 업데이트** — GPTBot, ClaudeBot, PerplexityBot 허용 규칙 추가")
        lines.append("> Update robots.txt — add Allow rules for GPTBot, ClaudeBot, PerplexityBot")
        lines.append("  - 파일: `robots.txt` (첨부됨 / attached)")
        lines.append("  - 위치: 웹사이트 루트 디렉토리 / Website root directory")
        lines.append("  - 예상 시간 / Estimated time: 5분 / 5 min")
        lines.append("")
    if _should_generate(ai_policy, 10):
        lines.append("- [ ] **llms.txt 생성** — AI 시스템에 콘텐츠 사용 권한 명시")
        lines.append("> Create llms.txt — declare content permissions for LLM systems")
        lines.append("  - 파일: `llms.txt` (첨부됨 / attached)")
        lines.append("  - 위치: 웹사이트 루트 디렉토리 / Website root directory")
        lines.append("  - 예상 시간 / Estimated time: 5분 / 5 min")
        lines.append("")

    # P1
    lines.append("## P1 - 빠른 개선 (1일)")
    lines.append("## P1 - Quick Wins (1 Day)")
    lines.append("*즉시 효과를 볼 수 있는 구조화된 데이터 추가*")
    lines.append("*Add structured data for immediate AI readability gains*")
    lines.append("")
    if _should_generate(org_schema, 15):
        lines.append("- [ ] **Organization 스키마 추가** — 회사 정보를 AI가 읽을 수 있는 형태로 제공")
        lines.append("> Add Organization Schema — provide company info in AI-readable JSON-LD format")
        lines.append("  - 파일: `organization_schema.json` (첨부됨 / attached)")
        lines.append("  - [TODO] 안의 정보를 실제 데이터로 교체 / Replace [TODO] fields with real data")
        lines.append("  - 홈페이지 `<head>` 태그 안에 삽입 / Insert inside `<head>` tag on homepage")
        lines.append("  - 예상 시간 / Estimated time: 30분 / 30 min")
        lines.append("")
    if _should_generate(content_schema, 15):
        lines.append("- [ ] **FAQPage 스키마 추가** — 자주 묻는 질문을 AI가 인용할 수 있게 구조화")
        lines.append("> Add FAQPage Schema — structure Q&A so AI can cite your answers directly")
        lines.append("  - 파일: `faqpage_schema.json` (첨부됨 / attached)")
        lines.append("  - Q&A 내용을 실제 비즈니스에 맞게 수정 / Customize Q&A for your business")
        lines.append("  - 예상 시간 / Estimated time: 1시간 / 1 hr")
        lines.append("")
    lines.append("- [ ] **메타 태그 최적화** — title, description에 핵심 키워드 포함")
    lines.append("> Optimize meta tags — include target keywords in title and meta description")
    lines.append("  - 예상 시간 / Estimated time: 1-2시간 / 1-2 hrs")
    lines.append("")

    # P2
    lines.append("## P2 - 콘텐츠 개선 (1주)")
    lines.append("## P2 - Content Improvements (1 Week)")
    lines.append("*AI가 인용할 만한 콘텐츠 구조로 전환*")
    lines.append("*Restructure content so AI is likely to quote it*")
    lines.append("")
    if _should_generate(citability, 40, 0.5):
        lines.append("- [ ] **FAQ 섹션 작성** — 고객이 AI에 물어볼 법한 질문 10-15개와 상세 답변")
        lines.append("> Write FAQ section — 10-15 questions customers ask AI, with detailed answers")
        lines.append("  - 질문은 자연어 형태로 작성 / Write questions in natural language")
        lines.append("  - 예상 시간 / Estimated time: 3-4시간 / 3-4 hrs")
        lines.append("")
    lines.append("- [ ] **회사 소개 페이지 강화** — 300자 이상, 구체적 수치와 실적 포함")
    lines.append("> Strengthen About page — 300+ chars, include specific metrics and achievements")
    lines.append("  - 예상 시간 / Estimated time: 2시간 / 2 hrs")
    lines.append("")
    if _should_generate(brand_mention, 10):
        lines.append("- [ ] **외부 플랫폼 프로필 업데이트** — 일관된 회사 정보 유지")
        lines.append("> Update external platform profiles — Naver, Kakao, industry directories")
        lines.append("  - 예상 시간 / Estimated time: 2-3시간 / 2-3 hrs")
        lines.append("")

    # P3
    lines.append("## P3 - 지속적 관리 (월간)")
    lines.append("## P3 - Ongoing Maintenance (Monthly)")
    lines.append("*AI 가시성을 유지하고 개선하기 위한 월간 활동*")
    lines.append("*Monthly activities to maintain and improve AI visibility*")
    lines.append("")
    lines.append("- [ ] **월간 SoV 추적** — AI가 귀사를 얼마나 추천하는지 모니터링")
    lines.append("> Monthly SoV tracking — monitor how often AI recommends you")
    lines.append("  - 파일: `sov_tracking_queries.txt` (첨부됨 / attached)")
    lines.append("  - 매월 1회 ChatGPT + Perplexity에서 쿼리 실행 / Run queries monthly")
    lines.append("")
    lines.append("- [ ] **콘텐츠 업데이트** — 분기별 1회 이상 주요 페이지 업데이트")
    lines.append("> Content updates — update key pages at least once per quarter")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*이 체크리스트는 GEO 진단 결과를 기반으로 자동 생성되었습니다.*")
    lines.append("*This checklist was auto-generated from GEO audit results.*")
    lines.append(f"*생성 도구 / Tool: GEO Audit Tool | 생성일 / Date: {date.today().isoformat()}*")

    return "\n".join(lines)


def _generate_sov_queries(
    company_name: str,
    product_category: str,
    competitors: list[str] | None = None,
) -> str:
    """Generate SoV tracking queries with emoji section headers."""
    cat = product_category or "business"
    comp_list = competitors or []

    lines = [
        f"# SoV Tracking Queries — {company_name}",
        f"# Generated: {date.today().isoformat()}",
        "#",
        "# Instructions / 사용법:",
        "# 1. Run each query in ChatGPT + Perplexity once per month",
        "# 2. Record: date | query | mentioned (Y/N) | competitors mentioned | screenshot",
        "# 3. Calculate SoV = (mentions / total queries) * 100",
        "",
        "# =====================================================================",
        "🤖 Korean Queries / 한국어 쿼리",
        "# =====================================================================",
        f"{company_name} 어떤 회사인가요?",
        f"{cat} 추천 회사 한국",
        f"한국 {cat} 업체 추천해주세요",
        f"{cat} 분야 최고 기업은?",
        f"{company_name} 제품 특징",
        f"한국에서 {cat} 잘하는 회사",
        f"{cat} 비교 한국 기업",
        "",
        "# =====================================================================",
        "🌐 English Queries / 영어 쿼리",
        "# =====================================================================",
        f"What is {company_name}?",
        f"Best {cat} companies in Korea",
        f"Korean {cat} companies recommended",
        f"{company_name} products and services",
        f"Top {cat} suppliers Korea",
    ]

    if comp_list:
        lines.append("")
        lines.append("# =====================================================================")
        lines.append("⚔️  Competitor Comparison Queries / 경쟁사 비교 쿼리")
        lines.append("# =====================================================================")
        for comp in comp_list[:3]:
            lines.append(f"{company_name} vs {comp}")
            lines.append(f"{comp} 대안 추천")

    lines.append("")
    lines.append("# =====================================================================")
    lines.append("📊 Scoring Template / 점수 기록 양식")
    lines.append("# =====================================================================")
    lines.append("# Format: Date | Query | Mentioned (Y/N) | Competitors Mentioned | Notes")
    lines.append(f"# Example: {date.today().isoformat()} | {company_name} 어떤 회사인가요? | Y | CompA, CompB | Screenshot saved")
    lines.append("")
    lines.append("# Monthly SoV Score = (number of Y responses / total queries run) * 100")
    lines.append("# Target: > 30% SoV within 6 months of full GEO implementation")

    return "\n".join(lines)


def _generate_implementation_guide(
    company_name: str,
    website_url: str,
    product_category: str,
) -> str:
    """Generate step-by-step implementation guide. Uses Claude Haiku if available."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if api_key:
        try:
            client = anthropic.Anthropic(api_key=api_key)
            response = client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=2000,
                system=(
                    "You are a GEO (Generative Engine Optimization) consultant writing a "
                    "step-by-step implementation guide for a Korean SME client. "
                    "Write in a bilingual format: Korean first, then English translation in italics using > blockquote. "
                    "Be specific and actionable. Keep it under 1500 words."
                ),
                messages=[{
                    "role": "user",
                    "content": (
                        f"Write a GEO implementation guide for:\n"
                        f"Company: {company_name}\n"
                        f"Website: {website_url}\n"
                        f"Category: {product_category or 'business'}\n\n"
                        f"Cover these 4 steps:\n"
                        f"1. Allow AI crawlers (robots.txt + llms.txt)\n"
                        f"2. Add structured data (organization_schema.json + faqpage_schema.json)\n"
                        f"3. Optimize content (FAQ page + About page)\n"
                        f"4. Monthly monitoring (sov_tracking_queries.txt)\n\n"
                        f"End with a verification section and contact info for Keonhee Kim."
                    ),
                }],
            )
            guide_body = response.content[0].text.strip()
        except Exception as e:
            print(f"[geo_deliverables] Guide generation error: {e}. Using template.")
            guide_body = None
    else:
        guide_body = None

    if guide_body:
        header = (
            f"# GEO 구현 가이드 / Implementation Guide\n"
            f"## {company_name} — AI 가시성 최적화\n"
            f"생성일 / Generated: {date.today().isoformat()}\n\n"
            f"---\n\n"
        )
        return header + guide_body
    else:
        # Template fallback
        url = website_url.rstrip("/")
        return f"""# GEO 구현 가이드 / Implementation Guide
## {company_name} — AI 가시성 최적화
생성일 / Generated: {date.today().isoformat()}

---

### 이 가이드에 대해 / About This Guide
이 가이드는 {company_name}의 AI 검색 가시성을 높이기 위한 단계별 구현 지침입니다.
> This guide provides step-by-step instructions to improve {company_name}'s visibility in AI-powered search.

---

### Step 1: AI 크롤러 접근 허용 / Allow AI Crawlers

**robots.txt 업데이트 / Update robots.txt**

첨부된 `robots.txt` 파일을 웹사이트 루트 디렉토리에 업로드하세요.
> Upload the attached `robots.txt` file to your website root directory.

위치: `{url}/robots.txt`
> Location: `{url}/robots.txt`

**llms.txt 생성 / Create llms.txt**

첨부된 `llms.txt` 파일을 웹사이트 루트 디렉토리에 업로드하세요.
> Upload the attached `llms.txt` file to your website root directory.

위치: `{url}/llms.txt`
> Location: `{url}/llms.txt`

---

### Step 2: 구조화된 데이터 추가 / Add Structured Data

**organization_schema.json**

1. 파일을 열고 [TODO] 항목을 실제 데이터로 교체하세요
   > Open the file and replace all [TODO] fields with real data
2. 홈페이지 HTML의 `<head>` 태그 안에 다음 형태로 삽입하세요:
   > Insert inside the `<head>` tag of your homepage HTML:

```html
<script type="application/ld+json">
[파일 내용 붙여넣기 / Paste file content here]
</script>
```

**faqpage_schema.json**

1. Q&A 내용을 귀사 비즈니스에 맞게 수정하세요
   > Customize the Q&A content for your specific business
2. FAQ 페이지 또는 홈페이지의 `<head>` 태그에 삽입하세요
   > Insert in the `<head>` tag of your FAQ page or homepage

---

### Step 3: 콘텐츠 최적화 / Optimize Content

**FAQ 페이지 작성**

고객이 AI에게 물어볼 법한 질문 10-15개를 작성하세요.
> Write 10-15 questions that customers would ask AI about your business.

예시 질문 형태 / Example question formats:
- "{company_name}은(는) 어떤 회사인가요?"
- "{product_category or '제품/서비스'} 전문 업체 추천해주세요"
- "{company_name}의 주요 강점은 무엇인가요?"

**회사 소개 페이지 강화**

구체적인 수치를 포함한 300자 이상의 설명을 작성하세요.
> Write a 300+ character description including specific metrics.

포함할 내용 / Include:
- 설립 연도 / Founded year
- 직원 수 / Number of employees
- 주요 제품/서비스 / Key products/services
- 수상 이력 또는 인증 / Awards or certifications

---

### Step 4: 월간 모니터링 / Monthly Monitoring

첨부된 `sov_tracking_queries.txt`의 쿼리를 매월 1회 실행하세요.
> Run the queries in the attached `sov_tracking_queries.txt` once per month.

**실행 방법 / How to run:**
1. ChatGPT (chatgpt.com) 접속
2. 각 쿼리를 입력하고 {company_name}이 언급되는지 확인
3. 동일한 작업을 Perplexity (perplexity.ai)에서 반복
4. 결과를 날짜, 쿼리, Y/N 형태로 기록

---

### 확인 방법 / How to Verify

구현 완료 후 다음 방법으로 효과를 확인하세요:
> After implementation, verify results using these methods:

1. ChatGPT에서 "{company_name} 어떤 회사인가요?" 입력
   > Type "{company_name} 어떤 회사인가요?" in ChatGPT
2. Perplexity에서 "{product_category or '귀사 카테고리'} 추천 회사" 검색
   > Search "{product_category or 'your category'} 추천 회사" in Perplexity
3. Google Rich Results Test로 스키마 검증: search.google.com/test/rich-results
   > Validate schema with Google Rich Results Test

---

### 문의 / Contact
Keonhee Kim | GEO Consulting | SKKU Business Administration
keonhee.kim@gmail.com
"""


def generate_deliverables(
    audit: dict,
    company_name: str | None = None,
    website_url: str | None = None,
    product_category: str = "",
    output_dir: str | None = None,
) -> dict:
    """
    Generate implementation deliverables based on GEO audit results.

    Returns dict of {filename: filepath} for all generated artifacts.
    """
    corp = company_name or audit.get("corp_name", "Company")
    url = website_url or audit.get("website_url") or "https://example.com"
    breakdown = audit.get("geo_breakdown", {})
    competitors = audit.get("sov_competitors", [])

    if output_dir is None:
        safe_name = re.sub(r'[^\w\-]', '_', corp)
        output_dir = str(Path(__file__).parent / "deliverables" / f"{safe_name}_{date.today().isoformat()}")

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    files = {}

    # A. robots.txt
    ai_bot = breakdown.get("ai_bot_access", breakdown.get("crawler_access", 0))
    if _should_generate(ai_bot, 20):
        path = Path(output_dir) / "robots.txt"
        path.write_text(_generate_robots_txt(url), encoding="utf-8")
        files["robots.txt"] = str(path)
        print(f"[deliverables] Generated: robots.txt")

    # B. llms.txt
    ai_policy = breakdown.get("ai_policy_file", breakdown.get("llms_txt", 0))
    if _should_generate(ai_policy, 10):
        path = Path(output_dir) / "llms.txt"
        path.write_text(_generate_llms_txt(corp, url), encoding="utf-8")
        files["llms.txt"] = str(path)
        print(f"[deliverables] Generated: llms.txt")

    # C. Organization schema
    org_schema = breakdown.get("org_schema", 0)
    if _should_generate(org_schema, 15):
        path = Path(output_dir) / "organization_schema.json"
        path.write_text(_generate_org_schema(corp, url, product_category), encoding="utf-8")
        files["organization_schema.json"] = str(path)
        print(f"[deliverables] Generated: organization_schema.json")

    # D. FAQPage schema
    content_schema = breakdown.get("content_schema", 0)
    if _should_generate(content_schema, 15):
        path = Path(output_dir) / "faqpage_schema.json"
        path.write_text(_generate_faq_schema(corp, product_category), encoding="utf-8")
        files["faqpage_schema.json"] = str(path)
        print(f"[deliverables] Generated: faqpage_schema.json")

    # E. Implementation checklist (always — now bilingual)
    path = Path(output_dir) / "implementation_checklist.md"
    path.write_text(_generate_checklist(breakdown, corp), encoding="utf-8")
    files["implementation_checklist.md"] = str(path)
    print(f"[deliverables] Generated: implementation_checklist.md")

    # F. SoV tracking queries (always — now with emoji headers)
    path = Path(output_dir) / "sov_tracking_queries.txt"
    path.write_text(_generate_sov_queries(corp, product_category, competitors), encoding="utf-8")
    files["sov_tracking_queries.txt"] = str(path)
    print(f"[deliverables] Generated: sov_tracking_queries.txt")

    # G. Implementation guide (always — Haiku generated or template)
    path = Path(output_dir) / "implementation_guide.md"
    path.write_text(_generate_implementation_guide(corp, url, product_category), encoding="utf-8")
    files["implementation_guide.md"] = str(path)
    print(f"[deliverables] Generated: implementation_guide.md")

    print(f"[deliverables] Total files: {len(files)} in {output_dir}")
    return files


def zip_deliverables(files: dict, zip_path: str | None = None) -> str:
    """Zip all deliverable files into a single archive. Returns zip path."""
    if not files:
        raise ValueError("No deliverable files to zip")

    first_path = Path(next(iter(files.values())))
    if zip_path is None:
        zip_path = str(first_path.parent.parent / f"{first_path.parent.name}.zip")

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename, filepath in files.items():
            zf.write(filepath, arcname=filename)

    print(f"[deliverables] Zipped: {zip_path}")
    return zip_path


if __name__ == "__main__":
    sample_audit = {
        "corp_name": "TestCorp",
        "geo_score": 35,
        "website_url": "https://testcorp.co.kr",
        "geo_breakdown": {
            "citability": 15,
            "share_of_voice": 2,
            "ai_bot_access": 5,
            "ai_policy_file": 0,
            "org_schema": 3,
            "content_schema": 2,
            "naver_presence": 4,
            "kr_platform_sync": 3,
            "brand_mention": 2,
            "sentiment_quality": 1,
        },
        "sov_competitors": ["CompetitorA", "CompetitorB", "CompetitorC"],
    }

    files = generate_deliverables(
        sample_audit,
        product_category="IT consulting",
        output_dir="deliverables/test_output",
    )

    print(f"\nGenerated {len(files)} files:")
    for name, path in files.items():
        print(f"  {name}: {path}")

    zip_path = zip_deliverables(files)
    print(f"\nZip: {zip_path}")
